# Generated by CoffeeScript 1.8.0
module.exports = (grunt) ->
  grunt.initConfig
    pkg: grunt.file.readJSON("package.json")
    bower:
      install:
        options:
          install: true
          copy: false
          cleanTargetDir: false
          cleanBowerDir: false

    copy:
      init:
        files: [
          {
            expand: true
            cwd: "bower_components/jquery/dist"
            src: 'jquery.min.js'
            dest: "js"
            filter: "isFile"
          }
          {
            expand: true
            cwd: "bower_components/trello_client"
            src: 'index.js'
            dest: 'js'
            filter: "isFile"
            rename: (dest, src) ->
              'js/trello_client.js'
          }
        ]

    watch:
      files: ["coffee/**/*.coffee"]
      tasks: ["coffee"]

    coffee:
      compile:
        files: [
          expand: true
          cwd: "coffee/"
          src: ["**/*.coffee"]
          dest: "js/"
          ext: ".js"
        ]
        options:
          bare: true

  grunt.loadNpmTasks "grunt-contrib-coffee"
  grunt.loadNpmTasks "grunt-contrib-watch"
  grunt.loadNpmTasks "grunt-bower-task"
  grunt.loadNpmTasks "grunt-contrib-copy"
  grunt.registerTask "init", [
    "bower:install"
    "copy"
  ]
  grunt.registerTask "default", [
    "copy"
    "coffee"
  ]
  return
