# Generated by CoffeeScript 1.8.0
module.exports = (grunt) ->
  grunt.initConfig
    pkg: grunt.file.readJSON("package.json")
    bower:
      install:
        options:
          install: true
          copy: false
          cleanTargetDir: false
          cleanBowerDir: false

    copy:
      develop:
        files: [
          {
            expand: true
            cwd: "bower_components/jquery/dist"
            src: 'jquery.js'
            dest: "js/"
            filter: "isFile"
          }
          {
            expand: true
            cwd: "bower_components/moment"
            src: 'moment.js'
            dest: "js/"
            filter: "isFile"
          }
          {
            expand: true
            cwd: "bower_components/lodash/dist"
            src: 'lodash.js'
            dest: "js/"
            filter: "isFile"
          }
          {
            expand: true
            cwd: "bower_components/bootstrap/dist/js"
            src: 'bootstrap.js'
            dest: "js/"
            filter: "isFile"
          }
          {
            expand: true
            cwd: "bower_components/bootstrap/dist/css"
            src: 'bootstrap.css'
            dest: "css/"
            filter: "isFile"
          }
          {
            expand: true
            cwd: "bower_components/bootstrap/dist/fonts"
            src: '*'
            dest: "fonts/"
            filter: "isFile"
          }
          {
            expand: true
            cwd: "bower_components/react"
            src: 'react.js'
            dest: 'js/'
            fileter: 'isFile'
          }
        ]
      release:
        files: [
          {
            expand: true
            cwd: "bower_components/jquery/dist"
            src: 'jquery.min.js'
            dest: "js/"
            filter: "isFile"
            rename: (dest, src) ->
              dest + 'jquery.js'
          }
          {
            expand: true
            cwd: "bower_components/moment/min"
            src: 'moment.min.js'
            dest: "js/"
            filter: "isFile"
            rename: (dest, src) ->
              dest + 'moment.js'
          }
          {
            expand: true
            cwd: "bower_components/lodash/dist"
            src: 'lodash.min.js'
            dest: "js/"
            filter: "isFile"
            rename: (dest, src) ->
              dest + 'lodash.js'
          }
          {
            expand: true
            cwd: "bower_components/bootstrap/dist/js"
            src: 'bootstrap.min.js'
            dest: "js/"
            filter: "isFile"
            rename: (dest, src) ->
              dest + 'bootstrap.js'
          }
          {
            expand: true
            cwd: "bower_components/bootstrap/dist/css"
            src: 'bootstrap.min.css'
            dest: "css/"
            filter: "isFile"
            rename: (dest, src) ->
              dest + 'bootstrap.css'
          }
          {
            expand: true
            cwd: "bower_components/bootstrap/dist/fonts"
            src: '*'
            dest: "fonts/"
            filter: "isFile"
          }
          {
            expand: true
            cwd: "bower_components/react"
            src: 'react.min.js'
            dest: 'js/'
            fileter: 'isFile'
            rename: (dest, src) ->
              dest + 'react.js'
          }
        ]

    watch:
      files: ["coffee/**/*.coffee"]
      tasks: ["cjsx"]

    cjsx:
      compile:
        files: [
          expand: true
          cwd: "coffee/"
          src: ["**/*.coffee"]
          dest: "js/"
          ext: ".js"
        ]
        options:
          bare: true
          sourceMap: true

  grunt.loadNpmTasks "grunt-coffee-react"
  grunt.loadNpmTasks "grunt-contrib-watch"
  grunt.loadNpmTasks "grunt-bower-task"
  grunt.loadNpmTasks "grunt-contrib-copy"
  grunt.registerTask "init", [
    "bower:install"
  ]
  grunt.registerTask "develop", [
    "copy:develop"
    "cjsx"
  ]
  grunt.registerTask "release", [
    "copy:release"
    "cjsx"
  ]
  grunt.registerTask "default", ["develop"]
  return
