# Generated by CoffeeScript 1.8.0
module.exports = (grunt) ->
  grunt.initConfig
    pkg: grunt.file.readJSON("package.json")
    bower:
      install:
        options:
          install: true
          copy: false
          cleanTargetDir: false
          cleanBowerDir: false

    copy:
      init:
        files: [
          {
            expand: true
            cwd: "bower_components/jquery/dist"
            src: 'jquery.js'
            dest: "js/"
            filter: "isFile"
            rename: (dest, src) ->
              dest + src
          }
          {
            expand: true
            cwd: "bower_components/react"
            src: 'react.js'
            dest: 'js/'
            fileter: 'isFile'
            rename: (dest, src) ->
              dest + src
          }
        ]
      build:
        files: [
          {
            expand: true
            cwd: "bower_components/jquery/dist"
            src: 'jquery.min.js'
            dest: "js/"
            filter: "isFile"
            rename: (dest, src) ->
              dest + 'jquery.js'
          }
          {
            expand: true
            cwd: "bower_components/react"
            src: 'react.min.js'
            dest: 'js/'
            fileter: 'isFile'
            rename: (dest, src) ->
              dest + 'react.js'
          }
        ]

    watch:
      files: ["coffee/**/*.coffee"]
      tasks: ["cjsx"]

    cjsx:
      compile:
        files: [
          expand: true
          cwd: "coffee/"
          src: ["**/*.coffee"]
          dest: "js/"
          ext: ".js"
        ]
        options:
          bare: true
          sourceMap: true

  grunt.loadNpmTasks "grunt-coffee-react"
  grunt.loadNpmTasks "grunt-contrib-watch"
  grunt.loadNpmTasks "grunt-bower-task"
  grunt.loadNpmTasks "grunt-contrib-copy"
  grunt.registerTask "init", [
    "bower:install"
    "copy:init"
  ]
  grunt.registerTask "default", [
    "copy:init"
    "cjsx"
  ]
  grunt.registerTask "build", [
    "copy:build"
    "cjsx"
  ]
  return
